-- ========================================================
-- MY SPECIAL ENGLISH : Supabase PostgreSQL Database Schema
-- 고1 내신 대비 비밀 노트 (Supabase SQL 에디터에서 원클릭 실행)
-- ========================================================

-- 1. 대단원 테이블 (lessons)
CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 단어 테이블 (vocab_words)
CREATE TABLE IF NOT EXISTS vocab_words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    word_no INTEGER NOT NULL,
    word TEXT NOT NULL,
    pos TEXT,
    meaning TEXT NOT NULL,
    eng_def TEXT,
    test_count INTEGER DEFAULT 0,
    wrong_count INTEGER DEFAULT 0,
    is_mastered BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_lesson_word UNIQUE(lesson_id, word_no)
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS idx_vocab_lesson ON vocab_words(lesson_id);
CREATE INDEX IF NOT EXISTS idx_vocab_wrong ON vocab_words(lesson_id, wrong_count DESC);

-- 3. 회차별 성적 이력 (test_records)
CREATE TABLE IF NOT EXISTS test_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT REFERENCES lessons(id) ON DELETE CASCADE,
    test_category TEXT NOT NULL DEFAULT 'VOCAB', -- 'VOCAB' | 'UNIT' | 'WRITING'
    test_title TEXT,                             -- 상세 시험명 (예: '3과 본문 핵심 서술형 영작')
    round INTEGER NOT NULL,
    test_mode TEXT NOT NULL DEFAULT 'ALL',       -- 'ALL' | 'WRONG_ONLY'
    score INTEGER NOT NULL,
    correct_count INTEGER NOT NULL,
    total_count INTEGER NOT NULL,
    stars_won INTEGER NOT NULL,
    test_date TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_test_category CHECK (test_category IN ('VOCAB', 'UNIT', 'WRITING'))
);

CREATE INDEX IF NOT EXISTS idx_records_lesson ON test_records(lesson_id);
CREATE INDEX IF NOT EXISTS idx_records_category ON test_records(lesson_id, test_category);
CREATE INDEX IF NOT EXISTS idx_records_date ON test_records(test_date DESC);

-- 4. 회차별 오답 상세 로그 (test_wrong_history)
CREATE TABLE IF NOT EXISTS test_wrong_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT REFERENCES test_records(id) ON DELETE CASCADE,
    word_id BIGINT REFERENCES vocab_words(id) ON DELETE CASCADE,
    user_answer TEXT,
    correct_answer TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wrong_history_record ON test_wrong_history(record_id);
CREATE INDEX IF NOT EXISTS idx_wrong_history_word ON test_wrong_history(word_id);

-- 5. 앱 메타데이터 테이블 (app_meta)
CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- --------------------------------------------------------
-- Row Level Security (RLS) 설정
-- 웹 프론트엔드(익명 키 anon)에서 직접 읽기/쓰기가 가능하도록 허용
-- --------------------------------------------------------
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE vocab_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_wrong_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_meta ENABLE ROW LEVEL SECURITY;

-- 기존 정책 삭제 후 재생성 (재실행 시 에러 방지)
DROP POLICY IF EXISTS "Public all lessons" ON lessons;
CREATE POLICY "Public all lessons" ON lessons FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public all vocab_words" ON vocab_words;
CREATE POLICY "Public all vocab_words" ON vocab_words FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public all test_records" ON test_records;
CREATE POLICY "Public all test_records" ON test_records FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public all test_wrong_history" ON test_wrong_history;
CREATE POLICY "Public all test_wrong_history" ON test_wrong_history FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public all app_meta" ON app_meta;
CREATE POLICY "Public all app_meta" ON app_meta FOR ALL TO anon USING (true) WITH CHECK (true);

-- --------------------------------------------------------
-- 기본 초기 데이터 (시드 데이터) 삽입
-- --------------------------------------------------------
INSERT INTO app_meta (key, value)
VALUES 
    ('total_stars', '0'),
    ('admin_pin', '0000')
ON CONFLICT (key) DO NOTHING;

-- 3과 대단원 기본 생성
INSERT INTO lessons (unit_name)
VALUES ('3. The Gift of Art (비상 홍민표)')
ON CONFLICT (unit_name) DO NOTHING;

-- 3과 공식 40단어 시드 데이터 입력
DO $$
DECLARE
    lid BIGINT;
BEGIN
    SELECT id INTO lid FROM lessons WHERE unit_name = '3. The Gift of Art (비상 홍민표)' LIMIT 1;
    
    IF lid IS NOT NULL THEN
        INSERT INTO vocab_words (lesson_id, word_no, word, pos, meaning, eng_def) VALUES
        (lid, 1, 'primary', '형', '주요한', 'first in importance or degree'),
        (lid, 2, 'inspiration', '명', '영감, 영감을 주는 것', 'someone or something that gives you ideas for doing something'),
        (lid, 3, 'exceptionally', '부', '유난히, 이례적으로', 'to a greater degree than normal'),
        (lid, 4, 'intense', '형', '강렬한', 'of extreme force, degree, or strength'),
        (lid, 5, 'feature', '동/명', '특징으로 삼다 / 특징, 특성', 'to have as an impressive attribute or aspect'),
        (lid, 6, 'recognizable', '형', '(쉽게) 알아볼 수 있는, 유명한', 'easy to become aware of'),
        (lid, 7, 'preference', '명', '선호', 'a greater liking for one option over another'),
        (lid, 8, 'emphasize', '동', '강조하다', 'to give special importance or value to something'),
        (lid, 9, 'depict', '동', '묘사하다', 'to show or represent by a drawing, painting, or other art forms'),
        (lid, 10, 'surroundings', '명', '(주위) 환경', 'everything that is around or near a person or place'),
        (lid, 11, 'direct', '형', '직접적인', 'going straight without anything else in between'),
        (lid, 12, 'shade', '명', '색조 / 그늘', 'a color, especially with regard to how light or dark it is'),
        (lid, 13, 'calming', '형', '진정시키는', 'making someone feel more relaxed and less emotional, worried, or upset'),
        (lid, 14, 'identity', '명', '정체성', 'the characteristics, feelings or beliefs that make people different from others'),
        (lid, 15, 'easel', '명', '이젤', 'a wooden frame that holds a picture which is being painted'),
        (lid, 16, 'associate', '동', '연관 짓다', 'to connect something with something else in one''s mind'),
        (lid, 17, 'figure', '명', '모습, 형상', 'a shape or bodily shape of a person'),
        (lid, 18, 'resemble', '동', '닮다', 'to look like or be similar to another person or thing'),
        (lid, 19, 'transformative', '형', '변화시키는', 'causing a marked change in someone or something'),
        (lid, 20, 'stimulate', '동', '자극하다', 'to encourage or rouse to action or effort'),
        (lid, 21, 'interpret', '동', '해석하다', 'to decide what the intended meaning of something is'),
        (lid, 22, 'century', '명', '세기, 100년', 'a period of 100 years'),
        (lid, 23, 'stone-faced', '형', '돌처럼 굳은 표정의 얼굴인', 'showing no emotion or expression on the face'),
        (lid, 24, 'norm', '명', '일반적인 것, 표준', 'a standard, model, or pattern regarded as typical for a group'),
        (lid, 25, 'photograph', '동/명', '사진 찍다 / 사진', 'to take a photograph of / a picture made using a camera'),
        (lid, 26, 'analyze', '동', '분석하다', 'to examine the details of something carefully in order to understand or explain it'),
        (lid, 27, 'yearbook', '명', '졸업 앨범', 'a book published once a year by a school or college, containing photos and information'),
        (lid, 28, 'portrait', '명', '초상화, 초상 사진', 'a painting, photograph, or drawing of a person, especially only a person''s face'),
        (lid, 29, 'measure', '동', '측정하다', 'to find the size, quantity, etc. of something in standard units'),
        (lid, 30, 'manners', '명', '예의범절', 'polite ways of treating other people and behaving in public'),
        (lid, 31, 'demand', '동', '요구하다', 'to ask for something in a very strong or urgent way'),
        (lid, 32, 'mean', '형/동', '비열한, 못된 / 의미하다', 'unkind or unpleasant / to express, indicate, or signify'),
        (lid, 33, 'spread', '명/동', '확산, 퍼짐 / 펼치다, 퍼지다', 'the action of opening out / to become known or used by more and more people'),
        (lid, 34, 'launch', '동', '시작하다, 착수하다', 'to start an activity, especially an organized one'),
        (lid, 35, 'celebration', '명', '기념, 축하', 'a special social event, such as a party, when you celebrate something'),
        (lid, 36, 'capture', '동', '포착하다, 담아내다', 'to succeed in recording, showing, or expressing something on film or art'),
        (lid, 37, 'on one''s own', '숙어', '혼자서', 'by oneself, alone without help'),
        (lid, 38, 'bring up', '숙어', '~을 불러일으키다, 화제를 꺼내다', 'to mention a subject or start talking about it'),
        (lid, 39, 'take ~ for granted', '숙어', '~을 당연하게 여기다', 'to believe something to be the truth without even thinking about it'),
        (lid, 40, 'follow suit', '숙어', '남이 한 대로 따라 하다', 'to do the same thing that someone else has just done')
        ON CONFLICT (lesson_id, word_no) DO UPDATE SET
            word = EXCLUDED.word,
            pos = EXCLUDED.pos,
            meaning = EXCLUDED.meaning,
            eng_def = EXCLUDED.eng_def;
    END IF;
END $$;
